dev:
  port: 5233
  mysql:
    test:
      adapter: mysql
      database: test
      username: root
      password: 123456
      host: localhost
      port: 3306
      idle_conns: 10
      open_conns: 100
      max_life_time: 200
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: 123456
    vhost: /
    pool:
      max_conn: 100
      max_producer_channel_pre_conn: 50
      max_consumer_channel_pre_conn: 3
  redis:
    host: localhost:6379
    password: 123456
    idleTimeout: 600
    maxIdle: 5
    maxActive: 30
  memcache:
    host: localhost:8499
  log:
    filename: server.log
    max_age: 15 #days
